version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=yii
      - MYSQL_PASSWORD=yii
      - MYSQL_ROOT_PASSWORD=yii
      - MYSQL_DATABASE=yii
    command: ["--default-authentication-plugin=mysql_native_password"]
